site:
    title: void* nigh
    subtitle: may the codes guide you.
    logo: -/images/avatar.png
    limit: 7
    theme: Saka
    comment: code-moe   # 这里填写你的多说域名short-name
    root:  #可选
    lang: zh
    url: http://code-moe.cc/
    link: "post/{year}/{month}/{title}.html"

authors:
    me:
        name: nigh
        intro: nigh is going home
        avatar: -/images/avatar.png

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "generator update"
        git push
