site:
    title: void* nigh
    subtitle: may the codes guide you.
    logo: -/images/avatar.png
    limit: 10
    theme: ink_Werttin-1.0.2-beta
    disqus: 
    root: . #可选
    lang: zh
    url: nigh.github.io
    # root: /blog

authors:
    me:
        name: nigh
        intro: nigh is going home
        avatar: -/images/avatar.png

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - ink_Werttin-1.0.2-beta/css
        - ink_Werttin-1.0.2-beta/js
        - ink_Werttin-1.0.2-beta/favicon.png
        - ink_Werttin-1.0.2-beta/robots.txt
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "generator update"
        git push
