site:
    title: void* nigh
    subtitle: may the codes guide you.
    logo: -/images/avatar.png
    limit: 7
    theme: Saka
    disqus: 
    root:  #可选
    lang: zh
    url: http://code-moe.cc/

authors:
    me:
        name: nigh
        intro: nigh is going home
        avatar: -/images/avatar.png

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - Saka/css
        - Saka/js
        - Saka/favicon.png
        - Saka/robots.txt
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "generator update"
        git push
