site:
    title: void* nigh
    subtitle: may the codes guide you.
    logo: -/images/avator.png
    limit: 10
    theme: theme
    disqus: somebody
    lang: en
    url: nigh.github.io
    # root: /blog

authors:
    me:
        name: nigh
        intro: nigh is going home
        avatar: -/avator.png

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - theme/css
        - theme/js
        - theme/favicon.png
        - theme/robots.txt
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "generator update"
        git push
